### ISSUE TITLE
Packages?

### ISSUE THREAD

**Issue by ArezalGame89** [Kiffolisk/downdb#1]
I don't know if this depends on the **debian** version i'm running or not, but uh, this happens
`downdb
cp: -r not specified; omitting directory './downdb`

okay hang on i gotta relogin using KDE

**Comment by Kiffolisk** [comment]
command you used?

**Comment by Kiffolisk** [comment]
oh wait. you might have tried copying it where a file named "downdb" and a directory named "downdb" exist. try moving the downdb file maybe

**Comment by ArezalGame89** [comment]
> oh wait. you might have tried copying it where a file named "downdb" and a directory named "downdb" exist. try moving the downdb file maybe

Okay wait a sec @Kiffolisk , i think i fixed it, is this normal state?:
```downdb
Usage:
        downdb command [options]

Commands:
        install - Installs a program from one of the databases selected (or the default one)

NOTES:
        This requires wget or curl!```

**Comment by Kiffolisk** [comment]
yes
